# Generated by Django 6.0.4 on 2026-04-29 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadre', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LkLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'lk_levels',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/images/')),
                ('stamp_image', models.ImageField(blank=True, null=True, upload_to='signatures/stamps/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
            ],
            options={
                'db_table': 'signatures',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LkBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('theme', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('registration_open', models.DateField(blank=True, null=True)),
                ('registration_close', models.DateField(blank=True, null=True)),
                ('registration_form_url', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('finished', 'Finished')], default='draft', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lk_batches', to=settings.AUTH_USER_MODEL)),
                ('lk_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='training.lklevel')),
            ],
            options={
                'db_table': 'lk_batches',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LkAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('final_grade', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('result_status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('assessed_at', models.DateTimeField(blank=True, null=True)),
                ('assessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lk_assessments', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='training.lkbatch')),
            ],
            options={
                'db_table': 'lk_assessments',
                'ordering': ['-assessed_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LkMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='training.lkbatch')),
                ('lk_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='training.lklevel')),
            ],
            options={
                'db_table': 'lk_materials',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LkAssessmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='training.lkassessment')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_details', to='training.lkmaterial')),
            ],
            options={
                'db_table': 'lk_assessment_details',
            },
        ),
        migrations.CreateModel(
            name='LkParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('university', models.CharField(blank=True, max_length=150)),
                ('faculty', models.CharField(blank=True, max_length=150)),
                ('major', models.CharField(blank=True, max_length=150)),
                ('semester', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('motivation', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='lk/participants/')),
                ('registration_status', models.CharField(choices=[('registered', 'Registered'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='registered', max_length=20)),
                ('graduation_status', models.CharField(choices=[('not_assessed', 'Not Assessed'), ('passed', 'Passed'), ('failed', 'Failed')], default='not_assessed', max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='training.lkbatch')),
                ('cadre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lk_participants', to='cadre.cadre')),
                ('commissariat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lk_participants', to='cadre.commissariat')),
            ],
            options={
                'db_table': 'lk_participants',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='lkassessment',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='training.lkparticipant'),
        ),
        migrations.CreateModel(
            name='LkCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_number', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='lk/certificates/')),
                ('print_count', models.IntegerField(default=0)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='training.lkassessment')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='training.lkparticipant')),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='training.signature')),
            ],
            options={
                'db_table': 'lk_certificates',
                'ordering': ['-issued_date', '-created_at'],
            },
        ),
    ]
