# Generated by Django 6.0.4 on 2026-04-29 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20)),
                ('birth_place', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('university', models.CharField(blank=True, max_length=150)),
                ('faculty', models.CharField(blank=True, max_length=150)),
                ('major', models.CharField(blank=True, max_length=150)),
                ('entry_year', models.IntegerField(blank=True, null=True)),
                ('lk1_year', models.IntegerField(blank=True, null=True)),
                ('cadre_status', models.CharField(choices=[('active', 'Active'), ('alumni', 'Alumni'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cadres/photos/')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'cadres',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='CadreLkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('passed', 'Passed'), ('failed', 'Failed')], default='registered', max_length=20)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'cadre_lk_histories',
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commissariat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('university', models.CharField(blank=True, max_length=150)),
                ('address', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
            ],
            options={
                'db_table': 'commissariats',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('profession', models.CharField(blank=True, max_length=150)),
                ('workplace', models.CharField(blank=True, max_length=150)),
                ('position', models.CharField(blank=True, max_length=150)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('lk1_year', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='alumni/photos/')),
                ('notes', models.TextField(blank=True)),
                ('cadre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumni_records', to='cadre.cadre')),
            ],
            options={
                'db_table': 'alumni',
                'ordering': ['full_name'],
            },
        ),
    ]
