# Generated by Django 6.0.4 on 2026-04-29 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadre', '0001_initial'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadrelkhistory',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadre_histories', to='training.lkbatch'),
        ),
        migrations.AddField(
            model_name='cadrelkhistory',
            name='cadre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lk_histories', to='cadre.cadre'),
        ),
        migrations.AddField(
            model_name='cadrelkhistory',
            name='lk_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cadre_histories', to='training.lklevel'),
        ),
        migrations.AddField(
            model_name='cadre',
            name='commissariat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadres', to='cadre.commissariat'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='commissariat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumni', to='cadre.commissariat'),
        ),
    ]
