# Generated by Django 6.0.4 on 2026-04-29 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsUploadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester_name', models.CharField(max_length=150)),
                ('requester_email', models.EmailField(blank=True, max_length=150)),
                ('requester_phone', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_requests/images/')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='news_requests/attachments/')),
                ('price', models.DecimalField(decimal_places=2, default=50000, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('waiting_payment', 'Waiting Payment'), ('paid', 'Paid'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published')], default='pending', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_requests', to='content.newscategory')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_news_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'news_upload_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsRequestPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=50000, max_digits=12)),
                ('payment_method', models.CharField(blank=True, max_length=100)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='news_requests/payment_proofs/')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unpaid', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_news_request_payments', to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='news_request.newsuploadrequest')),
            ],
            options={
                'db_table': 'news_request_payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
