# Generated by Django 6.0.4 on 2026-04-29 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('kader', 'Kader'), ('lk1', 'LK 1'), ('lk2', 'LK 2'), ('lk3', 'LK 3'), ('program', 'Program'), ('agenda', 'Agenda'), ('other', 'Other')], default='kader', max_length=30)),
                ('google_form_url', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_registration_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registration_forms',
                'ordering': ['title'],
            },
        ),
    ]
