# Generated by Django 6.0.4 on 2026-04-29 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('letter_number', models.CharField(blank=True, max_length=100)),
                ('recipient', models.CharField(blank=True, max_length=150)),
                ('recipient_email', models.EmailField(blank=True, max_length=150)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('letter_date', models.DateField(blank=True, null=True)),
                ('content', models.TextField(blank=True)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='letters/outgoing/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'outgoing_letters',
                'ordering': ['-letter_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('archive_number', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='archives/documents/')),
                ('archive_date', models.DateField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_document_archives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_archives',
                'ordering': ['-archive_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GmailIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=150)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expired_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected')], default='disconnected', max_length=20)),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gmail_integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gmail_integrations',
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_type', models.CharField(blank=True, max_length=100)),
                ('related_id', models.BigIntegerField(blank=True, null=True)),
                ('recipient_email', models.EmailField(blank=True, max_length=150)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('gmail_integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='administration.gmailintegration')),
            ],
            options={
                'db_table': 'email_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncomingLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('letter_number', models.CharField(blank=True, max_length=100)),
                ('sender', models.CharField(blank=True, max_length=150)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('letter_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='letters/incoming/')),
                ('status', models.CharField(choices=[('new', 'New'), ('processed', 'Processed'), ('archived', 'Archived')], default='new', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_incoming_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'incoming_letters',
                'ordering': ['-received_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitation_number', models.CharField(blank=True, max_length=100)),
                ('recipient', models.CharField(blank=True, max_length=150)),
                ('recipient_email', models.EmailField(blank=True, max_length=150)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True)),
                ('invitation_date', models.DateField(blank=True, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='letters/invitations/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invitations',
                'ordering': ['-invitation_date', '-created_at'],
            },
        ),
    ]
